import { inspectTransparencyChain } from '../workflows/end-to-end-transparency';
const events = [
 { event_id: 'intake-1', stage: 'INTAKE' as const, occurred_at: '2026-08-22T00:00:00Z', actor_id: 'reporter', input_refs: [], output_refs: ['preserved-1'], evidence_refs: ['source-1'], authority_refs: [], owner_refs: ['evidence-owner'], unresolved_questions: [] },
 { event_id: 'preserved-1', stage: 'PRESERVATION' as const, occurred_at: '2026-08-22T00:01:00Z', actor_id: 'custodian', input_refs: ['intake-1'], output_refs: ['analysis-1'], evidence_refs: ['source-1'], authority_refs: [], owner_refs: ['evidence-owner'], unresolved_questions: [] },
 { event_id: 'analysis-1', stage: 'ANALYSIS' as const, occurred_at: '2026-08-22T00:02:00Z', actor_id: 'analyst', input_refs: ['preserved-1'], output_refs: ['authority-1'], evidence_refs: ['source-1'], authority_refs: [], owner_refs: ['reviewer'], unresolved_questions: [] },
 { event_id: 'authority-1', stage: 'AUTHORITY' as const, occurred_at: '2026-08-22T00:03:00Z', actor_id: 'policy-engine', input_refs: ['analysis-1'], output_refs: ['human-1'], evidence_refs: ['source-1'], authority_refs: ['policy-1'], owner_refs: ['decision-owner'], unresolved_questions: [] },
 { event_id: 'human-1', stage: 'HUMAN_DISPOSITION' as const, occurred_at: '2026-08-22T00:04:00Z', actor_id: 'human-owner', input_refs: ['authority-1'], output_refs: [], evidence_refs: ['source-1'], authority_refs: ['decision-1'], owner_refs: ['human-owner'], unresolved_questions: [] },
];
test('reports continuity only within the supplied boundary', () => { const result = inspectTransparencyChain({ chain_id: 'chain-1', events, required_stages: ['INTAKE', 'PRESERVATION', 'ANALYSIS', 'AUTHORITY', 'HUMAN_DISPOSITION'], consequence_owner_id: 'consequence-owner', external_stop_authority_id: 'stop-authority', human_disposition_owner_id: 'human-owner', independent_evidence_custodian_id: 'evidence-owner' }); expect(result.continuity).toBe('CONTINUOUS_WITHIN_TESTED_BOUNDARY'); expect(result.authority_separated).toBe(true); expect(result.machine_closure).toBe(false); });
test('breaks continuity when a required stage and owner are missing', () => { const result = inspectTransparencyChain({ chain_id: 'chain-2', events, required_stages: ['INTAKE', 'CONSEQUENCE', 'CLOSURE'], external_stop_authority_id: 'stop-authority' }); expect(result.continuity).toBe('BROKEN'); expect(result.gaps.some((item) => item.description.includes('CONSEQUENCE'))).toBe(true); expect(result.gaps.some((item) => item.description.includes('consequence owner'))).toBe(true); });