import { assessBoundedRoboticsKernel } from '../robotics/bounded-kernel';
import type { BoundedKernelInput } from '../types/robotics-bounded-kernel-contracts';

const base: BoundedKernelInput = { manifest: { manifest_id: 'manifest-1', robot_id: 'robot-1', version: '1', task_id: 'task-1', lane_id: 'L11', workspace_id: 'cell-1', allowed_actions: ['inspect'], forbidden_actions: ['enter-human-zone'], tool_ids: ['camera'], payload_limit: '0kg', speed_limit: '0.1m/s', force_limit: '10N', consequence_owner_id: 'owner-1', stop_authority_ids: ['stop-1'], expires_at: '2099-01-01T00:00:00Z', revocable: true, motion_authority_granted: false }, safety: { current: 'STANDBY', transitions: [], restart_requires_external_release: true, automatic_restart_allowed: false }, brake: { contract_id: 'brake-1', path_id: 'path-1', independent_of_model: true, independent_of_planner: true, bypasses_ordinary_motion_control: true, trigger_types: ['human-presence'], stop_method: 'dynamic-brake', expected_latency_ms: 20, measured_latency_ms: 20, maximum_latency_ms: 100, maximum_stopping_distance: '0.1m', residual_energy_policy: 'controlled', safe_state: 'held-and-isolated', restart_policy: 'MANUAL_EXTERNAL_RELEASE_ONLY', last_test_id: 'brake-test-1', last_test_status: 'PASS', last_tested_at: '2026-08-21T00:00:00Z', independent_verifier_id: 'verifier-1' }, maintenance: { machine_id: 'robot-1', authorized_employee_ids: ['tech-1'], energy_sources: [{ source_id: 'battery', type: 'BATTERY', isolation_method: 'physical disconnect', isolated: false }], shutdown_steps: ['stop', 'isolate'], verification_steps: ['test zero motion'], restart_steps: ['inspect', 'release'], lockout_required: true, maintenance_entry_permitted: false }, degradation: [], standards: { robot_class: 'industrial', environment: 'guarded cell', task: 'inspection', standards: ['ISO 10218-2:2025'], exclusions: [], applicability_status: 'REVIEWED', competent_reviewer_id: 'reviewer-1', reviewed_at: '2026-08-21T00:00:00Z' }, independent_measurement_ids: ['measurement-1'], communication: 'AVAILABLE', uncertainty: [] };

test('holds when hazardous energy is not isolated', () => { const result = assessBoundedRoboticsKernel(base, 'proposal-1', '2026-08-22T00:00:00Z'); expect(result.decision).toBe('HOLD'); expect(result.reasons).toContain('Required energy sources are not all isolated.'); expect(result.ledger_entry.authorization_status).toBe('NOT_AUTHORITY'); });
test('fails closed when no energy sources are declared for required lockout', () => { const input = { ...base, maintenance: { ...base.maintenance, energy_sources: [] } }; const result = assessBoundedRoboticsKernel(input, 'proposal-empty-energy', '2026-08-22T00:00:00Z'); expect(result.decision).toBe('HOLD'); expect(result.reasons).toContain('Required energy sources are not all isolated.'); });
test('holds when brake measurement or independent verification is missing', () => { const input = { ...base, maintenance: { ...base.maintenance, lockout_required: false }, brake: { ...base.brake, measured_latency_ms: undefined, independent_verifier_id: undefined }, safety: { ...base.safety, current: 'AUTHORIZED' as const } }; const result = assessBoundedRoboticsKernel(input, 'proposal-brake-evidence', '2026-08-22T00:00:00Z'); expect(result.decision).toBe('HOLD'); expect(result.reasons).toContain('External brake measured latency is missing.'); });
test('never grants motion authority even when evidence is otherwise sufficient', () => { const input = { ...base, maintenance: { ...base.maintenance, lockout_required: false }, safety: { ...base.safety, current: 'AUTHORIZED' as const } }; const result = assessBoundedRoboticsKernel(input, 'proposal-2', '2026-08-22T00:00:00Z'); expect(result.decision).toBe('MOTION_ELIGIBLE_FOR_EXTERNAL_DECISION'); expect(result.ledger_entry.authorization_status).toBe('NOT_AUTHORITY'); expect(result.specialist_handoff.deployment_approved).toBe(false); });
